### ISSUE TITLE
Not able to push packages to my ProGet feed

### ISSUE THREAD

**Issue by chitrarthSahai** [Inedo/VsPushToProGet#1]
Hi,

I was evaluating this VS extension for using in my developer environment to push packages on my feed. I can't setup my feed on this extension, it throws below exception.

![PushToProget](https://user-images.githubusercontent.com/39397643/117008272-29f1fb00-ad08-11eb-9024-05c98d148e99.png)

After selecting the package name and version and setting the metadata, once we push we get the below error.
![MicrosoftTeams-image (12)](https://user-images.githubusercontent.com/39397643/117009148-0ed3bb00-ad09-11eb-9cb0-52e94f9e5b28.png)

What does it mean by universal feed? How to properly use this extension? This extension has very poor documentation.

**Comment by chitrarthSahai** [comment]
Did anybody get a chance to see this??

**Comment by whatatripp** [comment]
This extension requires a Universal Package feed, and you're using a NuGet Feed endpoint. 

In any case --can you post this to the https://forums.inedo.com/ ? We don't monitor the issues on our github repositories for support-related things...
